/// Generated by AssetsRefGenerator on 2022/02/14
class Res {
  static const String bg_image1 = "assets/images/bg_image1.jpg";
  static const String bg_image_web = "assets/images/bg_image_web.jpeg";
  static const String bg_image_web1 = "assets/images/bg_image_web1.jpeg";
  static const String shop2 = "assets/images/shop2.jpeg";
  static const String userImage1 = "assets/images/userImage1.JPG";
}
